It's a security risk to allow non-root users to write to directories in root's $PATH. This module provides inventory for reporting about directories in root's =$PATH= are world or group writable.

* Reporting

** Classes 
- =default:group_writable_dir_in_root_path= :: Namespace scoped class defined when at least one directory in root's =$PATH= is group writable.
- =default:world_writable_dir_in_root_path= :: Namespace scoped class defined when at least one directory in root's =$PATH= is world writable.

** Inventory
- =Group writable directories in root PATH= :: List of directories from root's =$PATH= found to be group writable.
- =Group writable directories gid in root PATH= :: List of =directory=<GROUP ID>=  entries from root's =$PATH= found to be group writable.
- =World writable directories in root PATH= :: List of directories from root's =$PATH= found to be world writable.

[[https://raw.githubusercontent.com/nickanderson/cfengine-writable-directories-in-root-path/main/inventory-writable-directories-in-root-path/host-info-page-inventory-world-group-writeable-dirs-in-root-path.png]]
